version: "3"

services: 
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/home/node
      - /home/node/node_modules
    links:
      - db
    environment: 
      MONGO_CONNECTION_STRING: mongodb://db:27017
  
  db:
    image: mongo:3
    volumes: 
      - mongodb:/data/db

volumes:
  mongodb:
